export const ROUTES = {
  HOME: {
    NAVIGATOR: "HOME_NAVIGATOR",
    HOME: "HOME",
  },

  SEARCH: {
    NAVIGATOR: "SEARCH_NAVIGATOR",
    SEARCH: "SEARCH",
  },

  FAVOURITES: {
    NAVIGATOR: "FAVOURITES_NAVIGATOR",
    FAVOURITES: "FAVOURITES",
  },

  PROFILE: {
    NAVIGATOR: "PROFILE_NAVIGATOR",
    PROFILE: "PROFILE",
  },
};
